version: 0.0
os: linux
files:
- destination: /var/www/application
  source: /
permissions: []
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    runas: root
  AfterInstall:
  - location: scripts/install.sh
    runas: root
  ApplicationStart:
  - location: scripts/start.sh
    runas: root
    timeout: 60
  ApplicationStop:
  - location: scripts/stop.sh
    runas: root
    timeout: 180
  ValidateService:
  - location: scripts/validate.sh
    timeout: 30
