# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce05a26d20a48b5af02225bcbc033e99d6210f0448ba3d5e38fa16cadc87160d8b7dfdd22842e8f24d1d6cdf4a3c4a6fe891ac455ab6ec2fbc6d1fa03b503198

test:
  secret_key_base: 678cb149263cde544e7f54364382e6bf311b226f304299708bfefef8a25c46707a57894a64951b0598cdb1ce37151556aefda1dff3e2eaeb82fc58dd3473c933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
